site_name: scLEMBAS
site_description: "This is a python package for mecahnistically modeling ligand responses at single-cell resolution."

repo_url: https://github.com/hmbaghdassarian/scLEMBAS
repo_name: hmbaghdassarian/scLEMBAS

theme: readthedocs
repo_url: https://github.com/hmbaghdassarian/human_me
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: true
          options:
            show_submodules: true

# theme: readthedocs
# repo_url: https://github.com/hmbaghdassarian/human_me
# plugins:
#   - search
#   - mkdocstrings:
#       default_handler: python
#       handlers:
#         python:
#           paths: scLEMBAS
#           selection:
#             docstring_style: "numpy"
#           rendering:
#             show_source: false
#           options:
#             show_submodules: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Home": index.md
  - "API": api.md
